import {World} from "./world.js";import {Player} from "./player.js";import {Inventory} from "./inventory.js";import {Engine} from "./engine.js";import {NPCManager} from "./npcs.js";import {EnemyManager} from "./enemies.js";import {BossManager} from "./bosses.js";import {renderCrafting} from "./crafting.js";import {setupControls} from "./controls.js";import {updateUI} from "./ui.js";import {saveGame,loadGame} from "./save.js";import {ITEMS,TILE} from "./data.js";
class Game{
 constructor(){this.canvas=document.getElementById("game");this.engine=new Engine(this.canvas);this.keys={};this.inventory=new Inventory();this.world=new World();this.player=new Player();this.npcs=new NPCManager();this.enemies=new EnemyManager();this.boss=new BossManager();this.mode="Survival";this.started=false;this.paused=false;this.invEl=document.getElementById("inventory");this.craftEl=document.getElementById("crafting");this.npcs.spawn(this.world,190,43,"Guide");this.npcs.spawn(this.world,225,43,"Merchant");setupControls(this);document.getElementById("survival").onclick=()=>this.start("Survival");document.getElementById("creative").onclick=()=>this.start("Creative");document.getElementById("load").onclick=()=>this.load();document.getElementById("resume").onclick=()=>this.togglePause();document.getElementById("save").onclick=()=>saveGame(this);this.loop()}
 start(mode){this.mode=mode;this.started=true;document.getElementById("menu").classList.add("hidden");this.inventory.seed();if(mode==="Creative"){for(let id of Object.keys(ITEMS))this.inventory.add(id,ITEMS[id].max)}}
 load(){let s=loadGame();if(!s)return alert("No saved world found.");this.mode=s.mode;this.started=true;document.getElementById("menu").classList.add("hidden");this.world.tiles=s.world;Object.assign(this.player,s.player);this.inventory.slots=s.inventory}
 togglePause(){if(!this.started)return;this.paused=!this.paused;document.getElementById("pause").classList.toggle("hidden",!this.paused)}
 toggleInventory(){if(!this.started)return;this.invEl.classList.toggle("hidden");if(!this.invEl.classList.contains("hidden"))this.renderInventory()}
 toggleCrafting(){if(!this.started)return;this.craftEl.classList.toggle("hidden");if(!this.craftEl.classList.contains("hidden"))renderCrafting(this.craftEl,this.inventory,()=>this.renderInventory())}
 renderInventory(){this.invEl.innerHTML="<h2>Inventory</h2><div class='invgrid'>"+this.inventory.slots.map((s,i)=>`<div class='itemslot' data-i='${i}'><i>${s?ITEMS[s.id].icon:""}</i>${s?`<b>${s.n}</b>`:""}</div>`).join("")+"</div><p>Press E to close</p>"}
 action(e){if(!this.started||this.paused)return;let r=this.canvas.getBoundingClientRect(),wx=e.clientX-r.left+this.engine.cam.x,wy=e.clientY-r.top+this.engine.cam.y,tx=Math.floor(wx/TILE),ty=Math.floor(wy/TILE),dx=tx-Math.floor(this.player.x/TILE),dy=ty-Math.floor(this.player.y/TILE);if(Math.hypot(dx,dy)>7)return;
  if(e.button===0){let id=this.world.get(tx,ty);if(id!=="air"){this.world.set(tx,ty,"air");let drop=["grass","dirt","stone","sand","wood","glass","copper","iron","gold","crystal","brick","hellstone"].includes(id)?id:null;if(drop&&this.mode!=="Creative")this.inventory.add(drop,1)}}else if(e.button===2){e.preventDefault();let s=this.inventory.slots[this.inventory.selected];if(s&&ITEMS[s.id].tile&&!this.world.solid(tx,ty)){this.world.set(tx,ty,ITEMS[s.id].tile);if(this.mode!=="Creative")this.inventory.take(s.id,1)}}}
 loop(){requestAnimationFrame(()=>this.loop());if(!this.started)return;updateUI(this);if(this.paused)return;this.player.update(this.world,this.keys);this.npcs.update(this.world,this.player);if(this.mode==="Survival")this.enemies.update(this.world,this.player);this.boss.update(this.player);if(this.player.hp<=0){this.player.hp=this.player.maxHp;this.player.x=this.world.spawn.x*24;this.player.y=this.world.spawn.y*24;alert("You were defeated and returned to spawn.")}this.engine.drawWorld(this.world,this.player,this.npcs,this.enemies,this.boss)}
}
document.addEventListener("contextmenu",e=>e.preventDefault());window.game=new Game();
